import '../styles.css';
import './router.css';
import { buildFullPdfReport } from './pdfReport.js';
import { getLeads, saveLead, updateLeadStatus, LEAD_STATUSES } from './leadsStore.js';

const CONFIG={productionPerKw:1650,buyRate:.64,sellRate:.48,installCostPerKw:2900,sqmPerKw:7,panelKw:.63,usableRoofFactor:.82,vatRate:.18,homeSystemLimitKw:22.5,defaultSelfUseShare:.4,electricityGrowthRate:.04,defaultPhone:'972547299727'};
const LOGO_SRC='https://static.wixstatic.com/media/e34422_f461fb2e8382455e8d0d7ba9d71eca1e~mv2.png/v1/fill/w_298,h_194,al_c,q_90,enc_avif,quality_auto/Solatrix%20Logo%20Sait%20Main.png';
const marker='/roof-check';
function basePath(){const p=window.location.pathname||marker,i=p.indexOf(marker);return i>=0?p.slice(0,i+marker.length):marker}
const BASE_PATH=basePath(),SITE_ROOT=`${BASE_PATH.replace(/\/roof-check$/,'')||''}/`;
const ROUTES=[['','ראשי'],['address','כתובת וחשבון'],['roof-type','סוג גג'],['roof-marking','סימון גג'],['obstacles','מכשולים'],['analysis','ניתוח'],['report','דוח'],['admin','Admin']].map(([slug,label],step)=>({step,slug,label,title:`${label} | Solatrix`}));
function pSlug(s){return s?`${BASE_PATH}/${s}`:`${BASE_PATH}/`} function pStep(s){return pSlug(ROUTES[s]?.slug||'')}
function norm(){let p=window.location.pathname||BASE_PATH;p=p.replace(/\/index\.html$/,'/').replace(/\/404\.html$/,'/');if(p===BASE_PATH)p=`${BASE_PATH}/`;return p.replace(/\/$/,'')===BASE_PATH?`${BASE_PATH}/`:p.replace(/\/$/,'')}
function route(){if(window.location.hash==='#admin')return ROUTES[7];return ROUTES.find(r=>pSlug(r.slug).replace(/\/$/,'')===norm().replace(/\/$/,''))||ROUTES[0]}
const presets=[{points:'17,58 77,42 86,78 24,88',area:74,factor:1},{points:'14,18 48,10 52,36 16,46',area:36,factor:.88},{points:'58,14 86,18 80,38 56,34',area:22,factor:.82}];
const state={step:route().step,address:'',monthlyBill:850,roofType:'',leadName:'',leadPhone:'',surfaces:[],draftPoints:[],obstacles:[],leadSent:false,menuOpen:false,analysisTimer:null,selectedLeadId:null};
function setTitle(){document.title=ROUTES[state.step]?.title||'Solatrix'}
function nav(s,{replace=false}={}){state.step=Math.max(0,Math.min(7,+s));state.menuOpen=false;setTitle();const p=pStep(state.step);if(window.location.pathname!==p)history[replace?'replaceState':'pushState']({step:state.step},'',p)}
function setStep(s,o={}){clearTimeout(state.analysisTimer);if(state.step===3&&s>3)finishDraft();nav(s,o);render();if(state.step===5)state.analysisTimer=setTimeout(()=>setStep(6),900)}
function fmt(v){return Math.round(+v||0).toLocaleString('he-IL')} function money(v){return '₪'+fmt(v)}
function logo(){return `<div class="logoMark" aria-label="Solatrix Energy"><img class="logoImage" src="${LOGO_SRC}" alt="Solatrix Energy" loading="eager" /></div>`}
function header(){const menu=[0,1,2,3,4,6].map(s=>`<a href="${pStep(s)}" data-action="step:${s}" class="${state.step===s?'active':''}">${ROUTES[s].label}</a>`).join('');return `<header class="siteHeader ${state.menuOpen?'menuOpen':''}"><div class="headerInner"><a class="brand" href="${SITE_ROOT}">${logo()}</a><div class="headerActions"><a class="headerCta" href="https://wa.me/${CONFIG.defaultPhone}" target="_blank" rel="noreferrer">WhatsApp</a><button class="menuBtn" data-action="toggleMenu">${state.menuOpen?'×':'☰'}</button></div></div><nav class="mobileMenu">${menu}<a href="${SITE_ROOT}">לאתר הראשי</a></nav></header>`}
function progress(){return state.step===0||state.step===7?'':`<div class="progressDots">${[1,2,3,4,5,6].map(s=>`<span class="${s<=state.step?'done':''}"></span>`).join('')}</div>`}
function decor(){return '<div class="cardDecor" aria-hidden="true"><i></i><i></i><i></i></div>'} function floats(){return '<div class="floatingDecor" aria-hidden="true"><span>☀️</span><span>⚡</span><span>🏠</span><span>📍</span></div>'}
function actions(t){return `<div class="actions"><button class="primaryBtn" data-action="next">${t}</button>${state.step>1?'<button class="ghostBtn" data-action="prev">חזרה</button>':''}</div>`}
function areaPoly(points){if(points.length<3)return 0;let s=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];s+=a.x*b.y-b.x*a.y}return Math.abs(s/2)}
function pStr(points){return points.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ')}
function draft(){return state.draftPoints.length>=3?{id:999,points:pStr(state.draftPoints),area:Math.max(18,Math.round(areaPoly(state.draftPoints)*.045)),factor:1}:null}
function activeSurfaces(){const d=draft();return d?[...state.surfaces,d]:state.surfaces}
function finishDraft(){const d=draft();if(d){state.surfaces=[...state.surfaces,{...d,id:state.surfaces.length+1}];state.draftPoints=[]}}
function clearMark(){state.surfaces=[];state.draftPoints=[]}
function addPoint(e,node){const r=node.getBoundingClientRect();const x=Math.max(0,Math.min(100,(e.clientX-r.left)/Math.max(r.width,1)*100));const y=Math.max(0,Math.min(100,(e.clientY-r.top)/Math.max(r.height,1)*100));if(state.roofType!=='sloped'&&state.surfaces.length)state.surfaces=[];state.draftPoints=[...state.draftPoints,{x,y}];render()}
function createSurface(i){return{id:i+1,...presets[i%presets.length]}} function ensure(){if(!state.surfaces.length&&!state.draftPoints.length)state.surfaces=[createSurface(0)]}
function surf(s){const usableArea=Math.max((+s.area||0)*CONFIG.usableRoofFactor,0),kw=usableArea/CONFIG.sqmPerKw;return{usableArea,kw,panels:Math.max(Math.floor(kw/CONFIG.panelKw),1)}}
function isHome(){return state.roofType!=='commercial'}
function calc(){ensure();const all=activeSurfaces(),potential=all.reduce((a,s)=>a+surf(s).kw,0),weighted=all.reduce((a,s)=>a+(s.factor||1)*surf(s).kw,0)/Math.max(potential,1),systemKw=isHome()?Math.min(potential,CONFIG.homeSystemLimitKw):potential,annualProduction=systemKw*CONFIG.productionPerKw*weighted,annualConsumption=((+state.monthlyBill||0)*12)/CONFIG.buyRate,selfConsumed=Math.min(annualProduction*CONFIG.defaultSelfUseShare,annualConsumption),exported=Math.max(annualProduction-selfConsumed,0),annualSavings=selfConsumed*CONFIG.buyRate+exported*CONFIG.sellRate,effectiveTariff=annualSavings/Math.max(annualProduction,1),selfUseShare=selfConsumed/Math.max(annualProduction,1)*100,exportShare=100-selfUseShare,costBeforeVat=systemKw*CONFIG.installCostPerKw,costWithVat=costBeforeVat*(1+CONFIG.vatRate),paybackBeforeVat=costBeforeVat/Math.max(annualSavings,1),paybackWithVat=costWithVat/Math.max(annualSavings,1);let gross25=0;for(let y=0;y<25;y++)gross25+=selfConsumed*CONFIG.buyRate*Math.pow(1+CONFIG.electricityGrowthRate,y)+exported*CONFIG.sellRate;const roofArea=all.reduce((a,s)=>a+(+s.area||0),0),usableArea=all.reduce((a,s)=>a+surf(s).usableArea,0),panels=Math.max(Math.floor(systemKw/CONFIG.panelKw),1),profit25WithVat=gross25-costWithVat;return{systemKw,roofPotentialKw:potential,weightedFactor:weighted,annualProduction,annualConsumption,selfConsumed,exported,annualSavings,effectiveTariff,selfUseShare,exportShare,cost:costBeforeVat,costBeforeVat,costWithVat,payback:paybackWithVat,paybackBeforeVat,paybackWithVat,profit25:profit25WithVat,profit25WithVat,gross25,avgTariff25:gross25/Math.max(annualProduction*25,1),panels,roofArea,usableArea}}
function saveCurrentLead(r=calc()){return saveLead({name:state.leadName||'ללא שם',phone:state.leadPhone||'',address:state.address||'',monthlyBill:state.monthlyBill,roofType:state.roofType,surfaces:activeSurfaces(),obstacles:state.obstacles,systemKw:r.systemKw,annualProduction:r.annualProduction,annualSavings:r.annualSavings,payback:r.paybackWithVat,profit25:r.profit25WithVat,status:'חדש'})}
function mapMock(interactive=false){const surfs=activeSurfaces();const polys=surfs.map((s,i)=>`<polygon class="surface ${i===surfs.length-1?'active':''}" points="${s.points}"></polygon>`).join('');const line=state.draftPoints.length>1?`<polyline class="draftLine" points="${pStr(state.draftPoints)}"></polyline>`:'';const dots=state.draftPoints.map((p,i)=>`<g class="draftPoint"><circle cx="${p.x}" cy="${p.y}" r="3"></circle><text x="${p.x}" y="${p.y-4}" text-anchor="middle">${i+1}</text></g>`).join('');const pins=state.obstacles.map((_,i)=>{const c=[[42,36],[66,56],[72,28],[35,64]][i%4];return `<circle cx="${c[0]}" cy="${c[1]}" r="3.8"></circle>`}).join('');return `<div class="mapPanel ${interactive?'interactiveMap':''}" ${interactive?'data-action="mapPoint"':''}><div class="mapBadge">${interactive?(state.draftPoints.length?`${state.draftPoints.length} נקודות`:'Tap to mark'):'Roof marked'}</div><div class="scanPulse"></div><svg class="roofCanvas" viewBox="0 0 100 100"><defs><pattern id="grid" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M 8 0 L 0 0 0 8" fill="none" /></pattern></defs><rect x="0" y="0" width="100" height="100" class="mapBase"></rect><rect x="0" y="0" width="100" height="100" fill="url(#grid)" class="mapGrid"></rect><path class="sunRay" d="M5 15 L35 42 M4 38 L34 52 M12 60 L42 62"></path><path class="building" d="M12 14 L86 9 L92 82 L18 90 Z"></path>${polys}${line}${dots}<g class="obstaclePins">${pins}</g></svg></div>`}
function heroScreen(){return `<section class="screen heroScreen">${floats()}<div class="heroGrid"><div class="card centerCard heroCard">${decor()}<div class="eyebrow">Roof Check by Solatrix</div><h1>בדיקת גג סולארית</h1><p class="heroText">תוך דקה מקבלים הערכה ראשונית: שטח שימושי, כמות פאנלים, ייצור שנתי ורווח צפוי.</p><div class="featureChips"><span>☀️ חישוב מהיר</span><span>📍 לפי כתובת</span><span>📄 דוח PDF מלא</span></div><button class="primaryBtn large" data-action="next">התחילו בדיקת גג</button></div><div class="visualCard"><div class="orbit orbitOne"></div><div class="orbit orbitTwo"></div><div class="miniRoof"><div class="roofTop"></div><div class="panelRows"><span></span><span></span><span></span><span></span></div></div><div class="visualStats"><b>PDF</b><span>דוח מלא</span></div><div class="visualStats second"><b>☀️</b><span>חישוב מהיר</span></div></div></div></section>`}
function addressScreen(){return `<section class="screen">${floats()}<div class="card focusCard">${decor()}${progress()}<div class="screenIcon">📍</div><h2>כתובת וחשבון חשמל</h2><p class="subText">החשבון החודשי עוזר לחשב כמה מהייצור יחסוך קנייה ב־₪${CONFIG.buyRate} וכמה יימכר ב־₪${CONFIG.sellRate}.</p><div class="fieldGroup"><label>כתובת הגג</label><input value="${state.address}" placeholder="לדוגמה: החרמון 10, חיפה" data-field="address" /></div><div class="fieldGroup"><label>חשבון חשמל חודשי משוער</label><input value="${state.monthlyBill}" inputmode="numeric" data-field="monthlyBill" /></div>${actions('מצא את הגג')}</div></section>`}
function roofScreen(){return `<section class="screen">${floats()}<div class="card focusCard">${decor()}${progress()}<div class="screenIcon">🏠</div><h2>איזה סוג גג?</h2><div class="roofOptions"><button class="roofOption ${state.roofType==='flat'?'selected':''}" data-action="roof:flat"><span>▰</span><b>גג שטוח</b><small>עד ${CONFIG.homeSystemLimitKw} kW במערכת ביתית</small></button><button class="roofOption ${state.roofType==='sloped'?'selected':''}" data-action="roof:sloped"><span>◭</span><b>גג לא אחיד / כמה צדדים</b><small>נסמן כל צד בנפרד</small></button><button class="roofOption ${state.roofType==='commercial'?'selected':''}" data-action="roof:commercial"><span>▦</span><b>גג מסחרי</b><small>ללא מגבלת 22.5 kW</small></button></div>${actions('המשך לסימון')}</div></section>`}
function drawScreen(){const d=state.draftPoints.length,c=activeSurfaces().length,sl=state.roofType==='sloped';return `<section class="screen mapScreen"><div class="card mapCard">${decor()}${progress()}<div class="screenIcon">✏️</div><h2>${sl?'סמנו כל צד של הגג':'סמנו את שטח הגג'}</h2><p class="subText">לחצו על פינות הגג לפי הסדר. כל לחיצה מוסיפה נקודה קטנה וקו כחול.</p>${mapMock(true)}<div class="markStatus">${d?`סומנו ${d} נקודות${d>=3?' — אפשר להמשיך':''}`:c?`סומנו ${c} שטחי גג`:'לחצו על פינות הגג כדי להתחיל סימון.'}</div><div class="drawFooter"><div class="actions compactActions">${sl&&d>=3?'<button class="primaryBtn" data-action="finishSide">סיים צד והוסף עוד</button>':''}<button class="ghostBtn" data-action="undoPoint" ${!d?'disabled':''}>בטל נקודה</button><button class="ghostBtn" data-action="clearRoof" ${(!d&&!c)?'disabled':''}>נקה סימון</button></div><button class="nextTextBtn" data-action="next" ${(d<3&&c===0)?'disabled':''}>סיימתי</button></div></div></section>`}
function obstaclesScreen(){const items=[['ac','מזגן','❄️'],['boiler','דוד','💧'],['shade','צל','🌳'],['access','יציאה לגג','🚪'],['solar','קולטים קיימים','☀️']];return `<section class="screen mapScreen"><div class="card mapCard">${decor()}${progress()}<div class="screenIcon">🧩</div><h2>מה נמצא על הגג?</h2>${mapMock()}<div class="obstacleGrid">${items.map(([k,l,i])=>`<button class="obstacle ${state.obstacles.includes(k)?'selected':''}" data-action="obstacle:${k}"><span>${i}</span>${l}</button>`).join('')}</div>${actions('המשך')}</div></section>`}
function analysisScreen(){return `<section class="screen">${floats()}<div class="card centerCard analysisCard">${decor()}<div class="loader"></div><h2>מנתחים את הגג...</h2><p class="subText">בודקים שטח שימושי, כיוונים, צריכה עצמית, מכירה לרשת והחזר השקעה.</p><div class="analysisBadges"><span>שטח</span><span>ייצור</span><span>תעריף משולב</span><span>ROI</span></div></div></section>`}
function tariffMix(r){const sw=Math.max(8,Math.min(92,r.selfUseShare)),ew=Math.max(8,Math.min(92,r.exportShare));return `<div class="tariffMix"><div class="mixHead"><b>תמהיל חיסכון ומכירה</b><span>תעריף אפקטיבי: ₪${r.effectiveTariff.toFixed(3)} לקוט״ש</span></div><div class="mixBar"><i style="width:${sw}%"></i><em style="width:${ew}%"></em></div><div class="mixLegend"><span><i></i>צריכה עצמית: ${fmt(r.selfConsumed)} kWh לפי ₪${CONFIG.buyRate}</span><span><em></em>מכירה לרשת: ${fmt(r.exported)} kWh לפי ₪${CONFIG.sellRate}</span></div></div>`}
function reportScreen(){const r=calc(),note=isHome()&&r.roofPotentialKw>CONFIG.homeSystemLimitKw?`<div class="successToast">מערכת ביתית מוגבלת ל-${CONFIG.homeSystemLimitKw} kW. פוטנציאל הגג לפי שטח: ${r.roofPotentialKw.toFixed(1)} kW.</div>`:'';return `<section class="screen reportScreen">${floats()}<div class="card reportCard">${decor()}<div class="eyebrow">דוח סולארי ראשוני</div><h2>הגג מתאים למערכת של כ-${r.systemKw.toFixed(1)} kW</h2><div class="reportHeroGraphic"><div><strong>${money(r.annualSavings)}</strong><span>חיסכון/הכנסה שנתית משוערת</span></div><div><strong>${r.paybackWithVat.toFixed(1)}</strong><span>שנים החזר כולל מע״מ</span></div></div>${note}${tariffMix(r)}<div class="resultsGrid"><div><span>עלות לפני מע״מ</span><b>${money(r.costBeforeVat)}</b></div><div><span>עלות כולל מע״מ</span><b>${money(r.costWithVat)}</b></div><div><span>שטח גג</span><b>${fmt(r.roofArea)} m²</b></div><div><span>שטח שימושי</span><b>${fmt(r.usableArea)} m²</b></div><div><span>פאנלים</span><b>${r.panels}</b></div><div><span>ייצור שנתי</span><b>${fmt(r.annualProduction)} kWh</b></div><div><span>ערך קוט״ש ממוצע</span><b>₪${r.effectiveTariff.toFixed(3)}</b></div><div><span>חיסכון/הכנסה שנתית</span><b>${money(r.annualSavings)}</b></div><div><span>החזר לפני מע״מ</span><b>${r.paybackBeforeVat.toFixed(1)} שנים</b></div><div><span>החזר כולל מע״מ</span><b>${r.paybackWithVat.toFixed(1)} שנים</b></div><div><span>חיסכון 25 שנים</span><b>${money(r.gross25)}</b></div><div><span>רווח 25 שנים כולל מע״מ</span><b>${money(r.profit25WithVat)}</b></div></div><div class="leadFields"><input placeholder="שם מלא" value="${state.leadName}" data-field="leadName" /><input placeholder="טלפון WhatsApp" value="${state.leadPhone}" data-field="leadPhone" /></div><button class="primaryBtn large" data-action="generatePdf">קבלו דוח PDF מלא</button>${state.leadSent?'<div class="successToast">הדוח נפתח והפנייה נשמרה.</div>':''}</div></section>`}
function adminScreen(){const leads=getLeads();return `<section class="screen adminScreen"><div class="card adminCard">${decor()}<div class="eyebrow">Solatrix CRM</div><h2>לוח בקרה לידים</h2><div class="adminStats"><div><span>סה״כ לידים</span><b>${leads.length}</b></div></div><div class="leadsTable"><table><thead><tr><th>שם</th><th>טלפון</th><th>כתובת</th><th>מערכת</th><th>סטטוס</th></tr></thead><tbody>${leads.length?leads.map(l=>`<tr><td>${l.name}</td><td>${l.phone||'-'}</td><td>${l.address||'-'}</td><td>${Number(l.systemKw||0).toFixed(1)} kW</td><td>${l.status}</td></tr>`).join(''):'<tr><td colspan="5">אין עדיין לידים.</td></tr>'}</tbody></table></div></div></section>`}
function generatePdfReport(){finishDraft();const r=calc();saveCurrentLead(r);const html=buildFullPdfReport({report:r,state,config:CONFIG,logoSrc:LOGO_SRC,formatNumber:fmt,formatMoney:money});const win=window.open('','_blank');if(!win)return;win.document.open();win.document.write(html);win.document.close();state.leadSent=true;render()}
function screen(){if(state.step===0)return heroScreen();if(state.step===1)return addressScreen();if(state.step===2)return roofScreen();if(state.step===3)return drawScreen();if(state.step===4)return obstaclesScreen();if(state.step===5)return analysisScreen();if(state.step===7)return adminScreen();return reportScreen()}
function act(a,n,e){if(n.disabled)return;if(a==='toggleMenu'){state.menuOpen=!state.menuOpen;render()}if(a==='closeMenu'){if(state.menuOpen){state.menuOpen=false;render()}}if(a==='next')setStep(state.step+1);if(a==='prev')setStep(state.step-1);if(a==='mapPoint')addPoint(e,n);if(a==='finishSide'){finishDraft();render()}if(a==='undoPoint'){state.draftPoints=state.draftPoints.slice(0,-1);render()}if(a==='clearRoof'){clearMark();render()}if(a==='generatePdf')generatePdfReport();if(a&&a.startsWith('step:'))setStep(+a.split(':')[1]);if(a&&a.startsWith('roof:')){state.roofType=a.split(':')[1];clearMark();render()}if(a&&a.startsWith('obstacle:')){const v=a.split(':')[1];state.obstacles=state.obstacles.includes(v)?state.obstacles.filter(i=>i!==v):[...state.obstacles,v];render()}}
function render(){const root=document.getElementById('root');root.innerHTML=`${header()}<main class="appShell" data-action="closeMenu">${screen()}</main>`;root.querySelectorAll('[data-action]').forEach(n=>n.addEventListener('click',e=>{const a=n.getAttribute('data-action');if(a!=='closeMenu')e.preventDefault();act(a,n,e)}));root.querySelectorAll('[data-field]').forEach(n=>n.addEventListener('input',()=>{state[n.getAttribute('data-field')]=n.value}))}
window.addEventListener('popstate',()=>{clearTimeout(state.analysisTimer);state.step=route().step;state.menuOpen=false;setTitle();render()});nav(state.step,{replace:true});render();